name: Unzip project

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip archive
        run: |
          unzip drin-main.zip
          shopt -s dotglob
          mv drin-main/* .
          rm -rf drin-main drin-main.zip

      - name: Commit unpacked files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "unpack project archive"
